# Use /KWdata/Elections/CD2Voters.txt as Mariadb csv type
# New layout has 47 columns as per FOIL_VOTER_LIST_LAYOUT V2.5(2/13/2023)
use voting;
drop table if exists `VotersCD2_24`;
CREATE TABLE `VotersCD2_24` (
                                `LASTNAME` varchar(50) NOT NULL,
                                `FIRSTNAME` varchar(50) DEFAULT NULL,
                                `MIDDLENAME` varchar(50) DEFAULT NULL,
                                `NAMESUFFIX` varchar(10) DEFAULT NULL,
                                `RADDNUMBER` varchar(10) DEFAULT NULL,
                                `RHALFCODE` varchar(10) DEFAULT NULL,
                                `RPREDIRECTION` varchar(10) DEFAULT NULL,
                                `RSTREETNAME` varchar(70) DEFAULT NULL,
                                `RPOSTDIRECTION` varchar(10) DEFAULT NULL,
                                `RAPARTMENTTYPE` varchar(10) DEFAULT NULL,
                                `RAPARTMENT` varchar(15) DEFAULT NULL,
                                `RADDRNONSTD` varchar(250) DEFAULT NULL,
                                `RCITY` varchar(50) DEFAULT NULL,
                                `RZIP5` varchar(5) DEFAULT NULL,
                                `RZIP4` varchar(4) DEFAULT NULL,
                                `MAILADD1` varchar(100) DEFAULT NULL,
                                `MAILADD2` varchar(100) DEFAULT NULL,
                                `MAILADD3` varchar(100) DEFAULT NULL,
                                `MAILADD4` varchar(100) DEFAULT NULL,
                                `DOB` date NOT NULL date_format='YYYMMDD',
                                `GENDER` varchar(1) DEFAULT NULL,
#                            `ENROLLMENT` enum('DEM', 'REP', 'CON', 'WOR', 'OTH', 'BLK'),
                                `ENROLLMENT` varchar(3) NOT NULL,
                                `OTHERPARTY` varchar(30) DEFAULT NULL,
                                `COUNTYCODE` int(2) DEFAULT NULL,
                                `ED` int(3) DEFAULT NULL,
                                `LD` int(3) DEFAULT NULL,
                                `TOWNCITY` varchar(30) DEFAULT NULL,
                                `WARD` varchar(3) DEFAULT NULL,
                                `CD` int(3) DEFAULT NULL,
                                `SD` int(3) DEFAULT NULL,
                                `AD` int(3) DEFAULT NULL,
                                `LASTVOTEDDATE` date DEFAULT NULL date_format='YYYYMMDD',
                                `PREVYEARVOTED` varchar(4) DEFAULT NULL,
                                `PREVCOUNTY` varchar(2) DEFAULT NULL,
                                `PREVADDRESS` varchar(100) DEFAULT NULL,
                                `PREVNAME` varchar(150) DEFAULT NULL,
                                `COUNTYVRNUMBER` varchar(50) DEFAULT NULL,
                                `REGDATE` date NOT NULL date_format='YYYYMMDD',
#                            `VRSOURCE` enum('AGCY', 'CBOE', 'DMV', 'LOCALREG', 'MAIL', 'SCHOOL'),
                                `VRSOURCE` varchar(10) DEFAULT NULL,
                                `IDREQUIRED` varchar(1) DEFAULT NULL,
                                `IDMET` varchar(1) DEFAULT NULL,
                                `STATUS` varchar(10) DEFAULT NULL,
                                `REASONCODE` varchar(15) DEFAULT NULL,
                                `INACT_DATE` date DEFAULT NULL date_format='YYYYMMDD',
                                `PURGE_DATE` date DEFAULT NULL date_format='YYYYMMDD',
                                `SBOEID` varchar(50) NOT NULL,
                                `VoterHistory` varchar(1500) DEFAULT NULL
) ENGINE=CONNECT
  DEFAULT CHARSET=latin1 table_type=CSV file_name='/KWdata/Elections/CD2Voters.txt' `header`=0 `sep_char`=',' quoted=1
